name: Deploy Documentation

on:
  push:
    branches:
      - main    # Deploy when main branch is updated
    paths:
      - 'docs/**'   # Only trigger when docs folder changes
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install mkdocstrings[python]    # For Python API documentation
      
      - name: Build and deploy documentation
        run: |
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}